name: Terraform deploy

run-name: Terraform deploying ${{ inputs.ENV_NAME }} module to ${{ inputs.ENV_NAME }} environment



on: 
    # push:
    #   # branches:
    #   #   - 'dev-**'
    #   paths:
    #     - 'infra/**'
    workflow_dispatch:
      inputs:
        ENV_NAME:
          description: Environment to deploy
          type: choice
          required: true
          default: dev
          options:
          - dev
          - staging
          - production
        MODULE_NAME:
          description: Module to deploy
          type: choice
          required: true
          options:
          - network
          - alb
          - asg
        



env:
    BUILD_NUMBER: ${{  github.run_number }}

jobs: 
    deploy-to-env:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
          working-directory: infra/terraform/environments/${{ inputs.ENV_NAME }}/eu-west-1/${{ inputs.MODULE_NAME }}
      steps:
      - name: clone repo
        uses: actions/checkout@v4
      
      - name: install terraform binary
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.5"

      - name: login to aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: setup ssh
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: github.com
          private-key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}
    
      - name: terraform init
        run: |
          terraform init

      - name: terraform validate
        run: |
          terraform validate
      
      - name: terraform plan
        run: |
          terraform plan -out=saved_plan
      
      - name: terraform apply
        run: |
          terraform apply -auto-approve saved_plan


