name: Test build

run-name: ${{ github.actor }} is executing Test build



on: [push]



jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
        - name: clone repo
          uses: actions/checkout@v4

        - name: print the current folder structure
          run: ls -la

