name: Test build

run-name: ${{ github.actor }} is executing Test build on ${{ inputs.ENV_NAME }} environment



on: 
    push:
    workflow_dispatch:
        inputs:
          ENV_NAME:
            description: 'Environment name'
            required: true
            type: choice
            default: dev
            options:
            - dev
            - staging
            - production
          MANUAL_RUN:
            description: 'Run manually?'
            required: false
            type: boolean
            default: false

env:
    BUILD_NUMBER: ${{  github.run_number }}

jobs:
    # test-build:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: clone repo
    #       uses: actions/checkout@v4

    #     - name: Login to Docker Hub
    #       uses: docker/login-action@v3
    #       with:
    #         username: ${{ secrets.DOCKER_USERNAME }}
    #         password: ${{ secrets.DOCKER_PASSWORD }} 

    #     - name: generate new version
    #       run: |
    #         commit_short_hash=$(git rev-parse --short=5 HEAD)
    #         new_tag=${{ inputs.ENV_NAME }}-${{  env.BUILD_NUMBER }}-$commit_short_hash
    #         echo "NEW_VERSION=$new_tag" >> $GITHUB_ENV
        
    #     - name: Build and push
    #       uses: docker/build-push-action@v6
    #       with:
    #         push: true
    #         tags: networkthor/webserver-cicd:${{  env.NEW_VERSION }}
    
    deploy-to-env:
      runs-on: ubuntu-latest
      steps:
      - name: configure ssh
        run: |
          mkdir -p ~/.ssh/aws
          echo ${{ secrets.SSH_PRIVATE_KEY }} >> ~/.ssh/aws/cicd-key.pem
          chmod 400 ~/.ssh/aws/cicd-key.pem
      
      - name: deploy to env
        run: |
          ssh -i ~/.ssh/aws/cicd-key.pem ubuntu@52.30.170.67
          ip a


