name: Test build

run-name: ${{ github.actor }} is executing Test build



on: [push]

env:
    BUILD_NUMBER: ${{  github.run_number }}

jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
        - name: clone repo
          uses: actions/checkout@v4

        - name: login to registry
          run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }}  --password-stdin
        
        - name: build new image
          run: docker build -t networkthor/webserver-cicd:${{  env.BUILD_NUMBER }} .
        
        - name: push to registry
          run: docker push networkthor/webserver-cicd:${{  env.BUILD_NUMBER }}

