name: Test build

run-name: ${{ github.actor }} is executing Test build



on: [push]

env:
    BUILD_NUMBER: ${{  github.run_number }}

jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
        - name: clone repo
          uses: actions/checkout@v4

        - name: login to registry
          run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }}  --password-stdin

        - name: generate new version
          run: |
            commit_short_hash=$(git rev-parse --short=5 HEAD)
            new_tag=${{  env.BUILD_NUMBER }}-$commit_short_hash
            echo "NEW_VERSION=$new_tag" >> $GITHUB_ENV
        
        - name: build new image
          run: |
            docker build -t networkthor/webserver-cicd:$NEW_VERSION .
        
        - name: push to registry
          run: |
            docker push networkthor/webserver-cicd:$NEW_VERSION

